python generate.py \
  --device 0 \
  --length 100 \
  --tokenizer_path cache/vocab_user.txt \
  --model_path model/final_model \
  --nsamples=4 \
  --prefix "只剩下钢琴" \
  --topp 1 \
  --temperature 0.8 \
  --fast_pattern \
  --save_samples \
  --save_samples_path sample/